### ISSUE TITLE
Support "priority", something like ".. @750"

### ISSUE THREAD

**Issue by thanhtrdang** [greis/ConstraintFormatter#1]
Have got a plan to support "priority", something like ".. @750"?

**Comment by greis** [comment]
Thank you for the suggestion. I just finished the implementation. Now you can add priorities as the following:

```
view1.top@750 == view2.bottom
```

See commit: https://github.com/greis/ConstraintFormatter/commit/48f8b7a26207eefd15060b6f02effbd54db46732

**Comment by thanhtrdang** [comment]
Should it be view1.top == view2.bottom @750? Does this syntax make more sense?
Thank you for your fix so fassst.

**Comment by greis** [comment]
I thought about that, but the priority is more related to the first view than the second one. Also there are already other operators for the second view.

```
// this looks better
view1.width@750 == 100
view1.width@850 == superview.width - 10

// instead of
view1.width == 100 @750
view1.width == superview.width - 10 @850
```

**Comment by thanhtrdang** [comment]
Ah 
1. I just refer to other libs or Apple, normally they put it in the end.
2. "In the end" that means a seperated part, not relate to first view or second view. It relates to contraint itself.
How do you think?
